### ISSUE TITLE
gaming

### ISSUE THREAD

**Issue by Havard20009** [ChosoMeister/Smart-DNS#1]
hello
is it possible to using smart dns for gaming ?
like fortnite or cod or other games ?
if is it possible how to update the domain files for adding new domain or servers
with original shecan we can use the dns for gaming 
and also has doh
thank you

**Comment by ChosoMeister** [comment]
Yes its can
You can clone and used on your own server with your modified domains

**Comment by ChosoMeister** [comment]
اگه جایی گیر کردی بگو بهت بگم دقیق چی کار کنی.

**Comment by Havard20009** [comment]
سلام
میخوام سرور بازی فورت نایت اظافه کنم چه جوری باید فایل دی ان اس آپدیت کرد
ممنون

**Comment by Havard20009** [comment]
فقط یه سوال دیگه اینکه این آی پی که ما زدیم میشه به عنوان دی ان سرور ؟
ای پی رو میشه همه جا به عنوان دی ان اس استفاده کرد؟
و جه جوری میشه تست کرد که درست نصب شده ؟

**Comment by ChosoMeister** [comment]
خوب گیرت اینجاست پورت ۵۳ رو روی سرور داری استفاده میکنی.
داره تو اررور هم بهت میگه دوستم
